/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19_management_system.forms.input;

import covid19_management_system.MY_CONNECTION;
import covid19_management_system.entity.CachLy;
import covid19_management_system.entity.Person;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author HieuPhung
 */
public class CachLyForm extends javax.swing.JFrame {

    /**
     * Creates new form CachLy
     */
    Person person = new Person();
    CachLy cachLy = new CachLy();
    MY_CONNECTION my_connection = new MY_CONNECTION();
    ButtonGroup bgBHYT = new ButtonGroup();

    public CachLyForm() {
        initComponents();
        this.setTitle("Khai báo thông tin cách ly");

        bgBHYT.add(jRadioButtonPersonBHYT_YES);
        bgBHYT.add(jRadioButtonPersonBHYT_NO);
    }

    public void clearFiles() {

        // remove text from all jtextfields
        jTextPersonCMT.setText(null);
        jTextPersonName.setText(null);
        jDateChooserPersonBirthday.setDate(new Date());
        jComboBoxPersonGender.setSelectedIndex(0);
        jTextFieldPersonPhone.setText(null);
        jTextFieldPersonGmail.setText(null);
        jTextAreaPersonAddress.setText(null);
        bgBHYT.clearSelection();
        jTextFieldPersonMSYT.setText(null);

        jDateNgayKhai.setDate(new Date());

        jComboBoxCachLyType.setSelectedIndex(0);
        jComboBoxCachLyLevel.setSelectedIndex(0);
        jDateCachLyDateStart.setDate(new Date());
        jTextAreaCachLyAddress.setText(null);
        jTextFieldCachLyRoomNum.setText(null);
        jTextFieldCachLyBedNum.setText(null);
        jTextFCachLyRoommateName.setText(null);

        jDateChooserTestDate.setDate(new Date());
        jTextFieldTestTime.setText(null);
        jComboBoxTestForm.setSelectedIndex(0);
        jTextFieldTestAddress.setText(null);
        jComboBoxTestResult.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPersonPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPersonGmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonPersonBHYT_YES = new javax.swing.JRadioButton();
        jRadioButtonPersonBHYT_NO = new javax.swing.JRadioButton();
        jComboBoxPersonGender = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPersonAddress = new javax.swing.JTextArea();
        jButtonEDIT = new javax.swing.JButton();
        jButtonADD = new javax.swing.JButton();
        jButtonREMOVE = new javax.swing.JButton();
        jButtonCLEAR = new javax.swing.JButton();
        jTextPersonCMT = new javax.swing.JTextField();
        jDateChooserPersonBirthday = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPersonMSYT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButtonSEARCH = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextPersonName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCachLyType = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxCachLyLevel = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jDateCachLyDateStart = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCachLyAddress = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldCachLyRoomNum = new javax.swing.JTextField();
        jTextFieldCachLyBedNum = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFCachLyRoommateName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jDateChooserTestDate = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldTestTime = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxTestForm = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldTestAddress = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jComboBoxTestResult = new javax.swing.JComboBox<>();
        jButtonShowTest = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jDateNgayKhai = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KHAI BÁO CÁCH LY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1238, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CMT/CCCD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 173, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số điện thoại: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jTextFieldPersonPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldPersonPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 298, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gmail: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jTextFieldPersonGmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldPersonGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 298, -1));

        jPanel4.setBackground(new java.awt.Color(51, 0, 204));

        jRadioButtonPersonBHYT_YES.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonPersonBHYT_YES.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonPersonBHYT_YES.setText("Có");

        jRadioButtonPersonBHYT_NO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonPersonBHYT_NO.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonPersonBHYT_NO.setText("Không");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonPersonBHYT_YES)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonPersonBHYT_NO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButtonPersonBHYT_YES)
                .addComponent(jRadioButtonPersonBHYT_NO))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, -1, -1));

        jComboBoxPersonGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxPersonGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Chọn giới tính -", "Nam", "Nữ", "Khác" }));
        jPanel1.add(jComboBoxPersonGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 170, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Địa chỉ: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jTextAreaPersonAddress.setColumns(20);
        jTextAreaPersonAddress.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextAreaPersonAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPersonAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 298, 150));

        jButtonEDIT.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonEDIT.setText("Sửa");
        jButtonEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDITActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 735, 86, 45));

        jButtonADD.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonADD.setText("Thêm mới");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 735, 141, 45));

        jButtonREMOVE.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonREMOVE.setText("Xóa");
        jButtonREMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREMOVEActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonREMOVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 735, 87, 45));

        jButtonCLEAR.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonCLEAR.setText("Làm mới");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 735, 145, 45));

        jTextPersonCMT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextPersonCMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 298, -1));

        jDateChooserPersonBirthday.setDateFormatString("dd/MM/yyyy");
        jDateChooserPersonBirthday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jDateChooserPersonBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 300, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Thẻ BHYT: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jTextFieldPersonMSYT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldPersonMSYT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 299, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mã số thẻ: ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, -1, -1));

        jButtonSEARCH.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonSEARCH.setText("Tìm kiếm");
        jButtonSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 735, 141, 45));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("THÔNG TIN NGƯỜI KHAI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Họ và tên:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jTextPersonName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextPersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPersonNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 298, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ngày sinh:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 42));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Giới tính:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("KHAI BÁO CÁCH LY:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 119, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Thông tin cách ly:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Loại cách ly:");

        jComboBoxCachLyType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxCachLyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Loại cách ly -", "Tập trung", "Tại nhà" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Mức độ:");

        jComboBoxCachLyLevel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxCachLyLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Mức -", "F0", "F1", "F2", "F3" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Bắt đầu:");

        jDateCachLyDateStart.setDateFormatString("dd/MM/yyyy");
        jDateCachLyDateStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Địa điểm cách ly:");

        jTextAreaCachLyAddress.setColumns(20);
        jTextAreaCachLyAddress.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextAreaCachLyAddress.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCachLyAddress);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Số phòng:");

        jTextFieldCachLyRoomNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldCachLyBedNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Số giường:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Tên người cùng phòng:");

        jTextFCachLyRoommateName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFCachLyRoommateName))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCachLyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateCachLyDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCachLyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCachLyRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCachLyBedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxCachLyType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jComboBoxCachLyLevel)
                        .addComponent(jLabel19))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jDateCachLyDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldCachLyRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextFCachLyRoommateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldCachLyBedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Thông tin test mẫu thử Covid19:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 270, -1));

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Thời điểm test:");

        jDateChooserTestDate.setDateFormatString("dd/MM/yyyy");
        jDateChooserTestDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Lần:");

        jTextFieldTestTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Hình thức test:");

        jComboBoxTestForm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxTestForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Hình thức test -", "PCR", "Test nhanh" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Nơi test:");

        jTextFieldTestAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Kết quả:");

        jComboBoxTestResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxTestResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Kết quả -", "Âm tính", "Dương tính" }));

        jButtonShowTest.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonShowTest.setText("SHOW");
        jButtonShowTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserTestDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTestForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTestTime, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonShowTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jTextFieldTestTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addComponent(jDateChooserTestDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBoxTestForm)
                    .addComponent(jButtonShowTest))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jComboBoxTestResult))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jTextFieldTestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 474, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Ngày khai:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, -1, -1));

        jDateNgayKhai.setDateFormatString("dd/MM/yyyy");
        jDateNgayKhai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jDateNgayKhai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPersonNameActionPerformed

    private void jButtonSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSEARCHActionPerformed

        String cmt = null;
        cmt = jTextPersonCMT.getText();
        if (cmt.trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Enter your CMT/CCCD to search !", "Empty CMT/CCCD", 2);
        } else {

            // search the person with person's CMT
            if (person.searchPerson(cmt) == false) {
                JOptionPane.showMessageDialog(rootPane, "Person not found !", "Search Person", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Thông tin cá nhân
                String name = null;
                String birthday = null;
                String gender = null;
                String bhyt = null;
                String bhyt_num = null;
                String phone = null;
                String email = null;
                String address = null;

                // Thông tin cách ly
                String ngayKhaiCL = null;
                int type = 0;
                int level = 0;
                String dateStart = null;
                String addressCL = null;
                int roomN = 0;
                int bedN = 0;
                String nameRoommate = null;
                
                // Thông tin test covid
                String dateTest = null;
                int timeTest = 0;
                int formTest = 0;
                String addressTest = null;
                int resultTest = 0;

//                ----- get ID Person -----
                int idPerson = 0;
                // connect to database to get data with cmt/cccd
                PreparedStatement psID;
                ResultSet rsID;
                String searchQueryID = "SELECT `id` FROM `people` WHERE `cmt`=?";
                try {
                    psID = my_connection.createConnection().prepareStatement(searchQueryID);
                    psID.setString(1, cmt);

                    rsID = psID.executeQuery();

                    while (rsID.next()) {
                        idPerson = rsID.getInt(1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
                }
//                ----- END get ID -----

                // Truy vấn và gán giá trị cho các biến
                // 1. Lấy ra thông tin cá nhân
                PreparedStatement ps1;
                ResultSet rs1;
                String searchQuery1 = "SELECT `name`,`birthday`,`gender`,`bhyt`,`bhyt_num`,`phone`,`email`,`address` FROM `people` WHERE `cmt`=?";
                try {
                    ps1 = my_connection.createConnection().prepareStatement(searchQuery1);
                    ps1.setString(1, cmt);

                    rs1 = ps1.executeQuery();

                    while (rs1.next()) {
                        name = rs1.getString(1);
                        birthday = rs1.getString(2);
                        gender = rs1.getString(3);
                        bhyt = rs1.getString(4);
                        bhyt_num = rs1.getString(5);
                        phone = rs1.getString(6);
                        email = rs1.getString(7);
                        address = rs1.getString(8);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(PersonForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                // đổ dữ liệu ra cách trường của form
                jTextPersonName.setText(name);

                try {
                    Date dateIn = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(birthday);
                    jDateChooserPersonBirthday.setDate(dateIn);
                } catch (ParseException ex) {
                    Logger.getLogger(DichTeForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                jComboBoxPersonGender.setSelectedItem(gender);

                if (bhyt.equals("Có")) {
                    jRadioButtonPersonBHYT_YES.setSelected(true);
                } else if (bhyt.equals("Không")) {
                    jRadioButtonPersonBHYT_NO.setSelected(true);
                }

                jTextFieldPersonMSYT.setText(bhyt_num);
                jTextFieldPersonPhone.setText(phone);
                jTextFieldPersonGmail.setText(email);
                jTextAreaPersonAddress.setText(address);

                // 2. Lấy thông tin cách ly
                PreparedStatement ps2;
                ResultSet rs2;
                String searchQuery2 = "SELECT `ngay_khai_cl`, `type`, `level`, `cl_date_start`, `cl_address`, `room_num`, `bed_num`, `roommate_name` FROM `cach_ly` WHERE `id_person`=?";
                try {
                    ps2 = my_connection.createConnection().prepareStatement(searchQuery2);
                    ps2.setInt(1, idPerson);

                    rs2 = ps2.executeQuery();

                    while (rs2.next()) {
                        // Thông tin cách ly
                        ngayKhaiCL = rs2.getString(1);
                        type = rs2.getInt(2);
                        level = rs2.getInt(3);
                        dateStart = rs2.getString(4);
                        addressCL = rs2.getString(5);
                        roomN = rs2.getInt(6);
                        bedN = rs2.getInt(7);
                        nameRoommate = rs2.getString(8);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Đổ dữ liệu ra form cách ly
                try {
                    Date dateIn = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(ngayKhaiCL);
                    jDateNgayKhai.setDate(dateIn);
                } catch (ParseException ex) {
                    Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                if(type != 0){
                    jComboBoxCachLyType.setSelectedIndex(type);
                }
                
                if(level != 0){
                    jComboBoxCachLyLevel.setSelectedIndex(level);
                }
                
                try {
                    Date dateIn = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(dateStart);
                    jDateCachLyDateStart.setDate(dateIn);
                } catch (ParseException ex) {
                    Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                jTextAreaCachLyAddress.setText(addressCL.trim());
                jTextFieldCachLyRoomNum.setText(Integer.valueOf(roomN).toString().trim());
                jTextFieldCachLyBedNum.setText(Integer.valueOf(bedN).toString().trim());
                jTextFCachLyRoommateName.setText(nameRoommate.trim());
                
                
                // 3. Lấy thông tin lần test cuối cùng
                PreparedStatement ps3;
                ResultSet rs3;
                String searchQuery3 = "SELECT `date_test`, `times_test`, `forms_test`, `address_test`, `result_test` FROM `test_covid` WHERE `id_person`=? ORDER BY `times_test` DESC LIMIT 1";
                try {
                    ps3 = my_connection.createConnection().prepareStatement(searchQuery3);
                    ps3.setInt(1, idPerson);

                    rs3 = ps3.executeQuery();

                    while (rs3.next()) {
                        // Thông tin test covid
                        dateTest = rs3.getString(1);
                        timeTest = rs3.getInt(2);
                        formTest = rs3.getInt(3);
                        addressTest = rs3.getString(4);
                        resultTest = rs3.getInt(5);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Đổ dữ liệu ra form cách ly
                try {
                    Date dateIn = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(dateTest);
                    jDateChooserTestDate.setDate(dateIn);
                } catch (ParseException ex) {
                    Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                jTextFieldTestTime.setText(Integer.valueOf(timeTest).toString().trim());
                
                if(formTest != 0){
                    jComboBoxTestForm.setSelectedIndex(formTest);
                }
                
                jTextFieldTestAddress.setText(addressTest.trim());
                
                if(resultTest != 0){
                    jComboBoxTestResult.setSelectedIndex(resultTest);
                }

            }
        }

    }//GEN-LAST:event_jButtonSEARCHActionPerformed

    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed

        this.clearFiles();

    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed

        // lấy idPerson
        int idPerson = 0;
        String cmt = null;
        cmt = jTextPersonCMT.getText();
        PreparedStatement ps;
        ResultSet rs;
        String searchQuery = "SELECT `id` FROM `people` WHERE `cmt`=?";
        try {
            ps = my_connection.createConnection().prepareStatement(searchQuery);
            ps.setString(1, cmt);

            rs = ps.executeQuery();

            while (rs.next()) {
                idPerson = rs.getInt(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        // ----- lấy xong idPerson -----

        // add cach ly database
        try {

            // date
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // theo chuan cua db dang sd
            String ngayKhaiCL = dateFormat.format(jDateNgayKhai.getDate());

            int type = jComboBoxCachLyType.getSelectedIndex();
            int level = jComboBoxCachLyLevel.getSelectedIndex();

            // date
            String dateStart = dateFormat.format(jDateCachLyDateStart.getDate());

            String addressCL = jTextAreaCachLyAddress.getText();
            int roomN = Integer.valueOf(jTextFieldCachLyRoomNum.getText());
            int bedN = Integer.valueOf(jTextFieldCachLyBedNum.getText());
            String nameRoommate = jTextFCachLyRoommateName.getText();
            
            // data test_covid
            String dateTest = dateFormat.format(jDateChooserTestDate.getDate());

            int timeTest = 0;
            timeTest = Integer.valueOf(jTextFieldTestTime.getText());
            int formTest = jComboBoxTestForm.getSelectedIndex();
            
            String addressTest = jTextFieldTestAddress.getText();
            int resultTest = jComboBoxTestResult.getSelectedIndex();

            if (cachLy.addCachLy(idPerson, ngayKhaiCL, type, level, dateStart, addressCL, roomN, bedN, nameRoommate)) {
                cachLy.addTestCovid(idPerson, dateTest, timeTest, formTest, addressTest, resultTest);
                JOptionPane.showMessageDialog(rootPane, "New Cach Ly added successfully !", "Add Cach Ly", JOptionPane.INFORMATION_MESSAGE);
                this.clearFiles();

            } else {
                JOptionPane.showMessageDialog(rootPane, "Cach Ly Form not added !", "Add Cach Ly Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Enter fields number !", "Fields Type Number Error", JOptionPane.ERROR_MESSAGE);
        }  

    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonShowTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowTestActionPerformed
        
        int timeTest = 0;
        timeTest = Integer.valueOf(jTextFieldTestTime.getText());
        
        // Thông tin test covid
        String dateTest = null;
        int formTest = 0;
        String addressTest = null;
        int resultTest = 0;
        
        // get idPerson
        int idPerson = 0;
        String cmt = null;
        cmt = jTextPersonCMT.getText();
        if (cmt.trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Enter your CMT/CCCD to search !", "Empty CMT/CCCD", 2);
        } else {
            // search the person with person's CMT
            if (person.searchPerson(cmt) == false) {
                JOptionPane.showMessageDialog(rootPane, "Person not found !", "Search Person", JOptionPane.INFORMATION_MESSAGE);
            } else {
                PreparedStatement psID;
                ResultSet rsID;
                String searchQueryID = "SELECT `id` FROM `people` WHERE `cmt`=?";
                try {
                    psID = my_connection.createConnection().prepareStatement(searchQueryID);
                    psID.setString(1, cmt);

                    rsID = psID.executeQuery();

                    while (rsID.next()) {
                        idPerson = rsID.getInt(1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
//        ----- get information test from test_covid database -----
        // connect to database to get data with cmt/cccd
        PreparedStatement ps;
        ResultSet rs;
        String searchQuery = "SELECT `date_test`, `forms_test`, `address_test`, `result_test` FROM `test_covid` WHERE `id_person`=? AND `times_test`=?";
        try {
            ps = my_connection.createConnection().prepareStatement(searchQuery);
            ps.setInt(1, idPerson);
            ps.setInt(2, timeTest);
            rs = ps.executeQuery();

            while (rs.next()) {
                
                // Thông tin test covid
                dateTest = rs.getString(1);
                formTest = rs.getInt(2);
                addressTest = rs.getString(3);
                resultTest = rs.getInt(4);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // đổ dữ liệu ra form test
        try {
            Date dateIn = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(dateTest);
            jDateChooserTestDate.setDate(dateIn);
        } catch (ParseException ex) {
            Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(formTest != 0){
            jComboBoxTestForm.setSelectedIndex(formTest);
        }

        jTextFieldTestAddress.setText(addressTest.trim());

        if(resultTest != 0){
            jComboBoxTestResult.setSelectedIndex(resultTest);
        }
        
        
        
    }//GEN-LAST:event_jButtonShowTestActionPerformed

    private void jButtonREMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREMOVEActionPerformed
        
        int idPerson = 0;
        // connect to database to get data with cmt/cccd
        String cmt = null;
        cmt = jTextPersonCMT.getText();
        PreparedStatement ps;
        ResultSet rs;
        String searchQuery = "SELECT `id` FROM `people` WHERE `cmt`=?";
        try {
            ps = my_connection.createConnection().prepareStatement(searchQuery);
            ps.setString(1, cmt);

            rs = ps.executeQuery();

            while (rs.next()) {
                idPerson = rs.getInt(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DichTeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        // => Đến đây là có idPerson -----
        
        // Find idCachLy in cach_ly database
        int idCachLy = 0;
        String searchQueryCachLy = "SELECT `id` FROM `cach_ly` WHERE `id_person`=?";
        try {
            ps = my_connection.createConnection().prepareStatement(searchQueryCachLy);
            ps.setInt(1, idPerson);

            rs = ps.executeQuery();

            while (rs.next()) {
                idCachLy = rs.getInt(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(CachLyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Bắt đầu xóa !!!
        try {

            // trong check if duoi, da co edit database !!!
            if (cachLy.removeCachLy(idCachLy)) {
                cachLy.removeTest(idPerson);
                JOptionPane.showMessageDialog(rootPane, "Cach Ly deleted successfully !", "Remove Khai Bao Cach Ly", JOptionPane.INFORMATION_MESSAGE);
                this.clearFiles();
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cach Ly not deleted !", "Remove Cach Ly Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Enter the cachLy's id (Number) !", "Cach Ly Id Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonREMOVEActionPerformed

    private void jButtonEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDITActionPerformed
        
        int idPerson = 0;
        String cmt_temp = null;
        cmt_temp = jTextPersonCMT.getText();
        PreparedStatement ps;
        ResultSet rs;
        String searchQuery = "SELECT `id` FROM `people` WHERE `cmt`=?";
        try {
            ps = my_connection.createConnection().prepareStatement(searchQuery);
            ps.setString(1, cmt_temp);
            rs = ps.executeQuery();

            while (rs.next()) {
                idPerson = rs.getInt(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DichTeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        // => Đến đây đã có idPerson -----
        
        // edit the dich_te database
        try {

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // theo chuan cua db dang sd
            String ngayKhaiCL = dateFormat.format(jDateNgayKhai.getDate());

            int type = jComboBoxCachLyType.getSelectedIndex();
            int level = jComboBoxCachLyLevel.getSelectedIndex();

            // date
            String dateStart = dateFormat.format(jDateCachLyDateStart.getDate());

            String addressCL = jTextAreaCachLyAddress.getText();
            int roomN = Integer.valueOf(jTextFieldCachLyRoomNum.getText());
            int bedN = Integer.valueOf(jTextFieldCachLyBedNum.getText());
            String nameRoommate = jTextFCachLyRoommateName.getText();
            
            // data test_covid
            String dateTest = dateFormat.format(jDateChooserTestDate.getDate());

            int timeTest = 0;
            timeTest = Integer.valueOf(jTextFieldTestTime.getText());
            int formTest = jComboBoxTestForm.getSelectedIndex();
            
            String addressTest = jTextFieldTestAddress.getText();
            int resultTest = jComboBoxTestResult.getSelectedIndex();
            
            
            // xóa trước các bảng nếu có
            
            try {
                // trong check if duoi, da co edit database !!!
                if (cachLy.removeOneTest(timeTest)) {
//                    JOptionPane.showMessageDialog(rootPane, "Dich Te deleted successfully !", "Remove Khai Bao DichTe", JOptionPane.INFORMATION_MESSAGE);
//                    this.clearFiles();

                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Dich Te not deleted !", "Remove Dich Te Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (NumberFormatException ex) {
//                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Enter the dichTe's id (Number) !", "Dich Te Id Error", JOptionPane.ERROR_MESSAGE);
            }
            
            // delete bảng test

            // edit
            if (cachLy.editCachLy(idPerson, ngayKhaiCL, type, level, dateStart, addressCL, roomN, bedN, nameRoommate)) {
                // thêm mới
                cachLy.addTestCovid(idPerson, dateTest, timeTest, formTest, addressTest, resultTest);
                JOptionPane.showMessageDialog(rootPane, "Dich Te update successfully !", "Update Dich Te", JOptionPane.INFORMATION_MESSAGE);
                this.clearFiles();
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Dich Te Form not updated !", "Update Dich Te Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Enter fields number !", "Fields Type Number Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonEDITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CachLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CachLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CachLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CachLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CachLyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JButton jButtonEDIT;
    private javax.swing.JButton jButtonREMOVE;
    private javax.swing.JButton jButtonSEARCH;
    private javax.swing.JButton jButtonShowTest;
    private javax.swing.JComboBox<String> jComboBoxCachLyLevel;
    private javax.swing.JComboBox<String> jComboBoxCachLyType;
    private javax.swing.JComboBox<String> jComboBoxPersonGender;
    private javax.swing.JComboBox<String> jComboBoxTestForm;
    private javax.swing.JComboBox<String> jComboBoxTestResult;
    private com.toedter.calendar.JDateChooser jDateCachLyDateStart;
    private com.toedter.calendar.JDateChooser jDateChooserPersonBirthday;
    private com.toedter.calendar.JDateChooser jDateChooserTestDate;
    private com.toedter.calendar.JDateChooser jDateNgayKhai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButtonPersonBHYT_NO;
    private javax.swing.JRadioButton jRadioButtonPersonBHYT_YES;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCachLyAddress;
    private javax.swing.JTextArea jTextAreaPersonAddress;
    private javax.swing.JTextField jTextFCachLyRoommateName;
    private javax.swing.JTextField jTextFieldCachLyBedNum;
    private javax.swing.JTextField jTextFieldCachLyRoomNum;
    private javax.swing.JTextField jTextFieldPersonGmail;
    private javax.swing.JTextField jTextFieldPersonMSYT;
    private javax.swing.JTextField jTextFieldPersonPhone;
    private javax.swing.JTextField jTextFieldTestAddress;
    private javax.swing.JTextField jTextFieldTestTime;
    private javax.swing.JTextField jTextPersonCMT;
    private javax.swing.JTextField jTextPersonName;
    // End of variables declaration//GEN-END:variables
}
