/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19_management_system.views;

import covid19_management_system.controllers.cachlyController.ShowTableCachLyController;
import covid19_management_system.views.CachLy.AddCachLy;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author HieuPhung
 */
public class CachLyManage extends javax.swing.JFrame {

    /**
     * Creates new form CachLyManage
     */
    ShowTableCachLyController showTableCachLyController = new ShowTableCachLyController();
    public CachLyManage() {
        initComponents();
        this.setTitle("Quản lý thông tin khai báo cách ly y tế");
        
        // confirm de thuc hien dong
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đóng không ?", "Xác nhận thao tác", JOptionPane.YES_NO_OPTION) == 0) {
                    dispose();
                }
            }
        });
    }
    
    public void settingTableShowCachLy() {
//        jTableKhaiCachLy.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
//        jTableKhaiCachLy.getColumnModel().getColumn(0).setPreferredWidth(1);
//        jTableKhaiCachLy.getColumnModel().getColumn(1).setPreferredWidth(115);
//        jTableKhaiCachLy.getColumnModel().getColumn(2).setPreferredWidth(50);
//        jTableKhaiCachLy.getColumnModel().getColumn(3).setPreferredWidth(20);
//        jTableKhaiCachLy.getColumnModel().getColumn(4).setPreferredWidth(150);
//        jTableKhaiCachLy.getColumnModel().getColumn(5).setPreferredWidth(50);
//        jTableKhaiCachLy.getColumnModel().getColumn(6).setPreferredWidth(50);
//        jTableKhaiDichTe.getColumnModel().getColumn(7).setPreferredWidth(20);
//        jTableKhaiDichTe.getColumnModel().getColumn(8).setPreferredWidth(20);
//        jTableKhaiDichTe.getColumnModel().getColumn(9).setPreferredWidth(170);
//        jTableKhaiDichTe.getColumnModel().getColumn(10).setPreferredWidth(170);

        jTableKhaiCachLy.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTFSearchByCMT = new javax.swing.JTextField();
        jButtonSearchCachLy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonShowInfoCachLy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhaiCachLy = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonAddCachLy = new javax.swing.JButton();
        jButtonEditCachLy = new javax.swing.JButton();
        jButtonDeleteCachLy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButtonXemChiTiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ THÔNG TIN KHAI BÁO CÁCH LY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jTFSearchByCMT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonSearchCachLy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSearchCachLy.setText("TÌM KIẾM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TÌM KIẾM THEO CMT:");

        jButtonShowInfoCachLy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonShowInfoCachLy.setText("SHOW ALL");
        jButtonShowInfoCachLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowInfoCachLyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFSearchByCMT, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearchCachLy)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowInfoCachLy)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSearchByCMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchCachLy)
                    .addComponent(jLabel2)
                    .addComponent(jButtonShowInfoCachLy))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jTableKhaiCachLy.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTableKhaiCachLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và tên", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại", "Ngày khai", "TxCovid", "Từ vùng dịch", "Triệu chứng", "Bệnh"
            }
        )

        // make the jtable cells not edittable
        {public boolean isCellEditTable(int row, int column){
            return false;
        }}

    );
    jTableKhaiCachLy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jTableKhaiCachLy.setGridColor(new java.awt.Color(255, 255, 0));
    jTableKhaiCachLy.setRowHeight(25);
    jTableKhaiCachLy.setSelectionBackground(new java.awt.Color(0, 102, 51));
    jTableKhaiCachLy.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableKhaiCachLyMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jTableKhaiCachLyMouseEntered(evt);
        }
    });
    jScrollPane1.setViewportView(jTableKhaiCachLy);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addContainerGap()))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 532, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap()))
    );

    jPanel5.setBackground(new java.awt.Color(255, 204, 204));

    jButtonAddCachLy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonAddCachLy.setText("THÊM MỚI");
    jButtonAddCachLy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddCachLyActionPerformed(evt);
        }
    });

    jButtonEditCachLy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonEditCachLy.setText("SỬA");
    jButtonEditCachLy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditCachLyActionPerformed(evt);
        }
    });

    jButtonDeleteCachLy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonDeleteCachLy.setText("XÓA");
    jButtonDeleteCachLy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonDeleteCachLyActionPerformed(evt);
        }
    });

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("Nhập mã hộ khẩu:");

    jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton5.setText("SHOW");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButtonXemChiTiet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonXemChiTiet.setText("CHI TIẾT");
    jButtonXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonXemChiTietActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(0, 2, Short.MAX_VALUE))
                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddCachLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditCachLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(73, 73, 73)
            .addComponent(jButtonAddCachLy)
            .addGap(18, 18, 18)
            .addComponent(jButtonEditCachLy)
            .addGap(18, 18, 18)
            .addComponent(jButtonDeleteCachLy)
            .addGap(18, 18, 18)
            .addComponent(jButtonXemChiTiet)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addGap(18, 18, 18)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jButton5)
            .addGap(116, 116, 116))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddCachLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCachLyActionPerformed
        jTFSearchByCMT.setText("");
        AddCachLy temp = new AddCachLy();
        temp.setLocationRelativeTo(null);
        temp.setResizable(false);
        temp.setVisible(true);
        
        temp.getjButtonAddCachLy().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                temp.addNewCachLy();
                
//                settingTableShowCachLy();
//                showTableCachLyController.showCachLy(jTableKhaiCachLy);
            }
        });
    }//GEN-LAST:event_jButtonAddCachLyActionPerformed

    private void jButtonEditCachLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditCachLyActionPerformed

    }//GEN-LAST:event_jButtonEditCachLyActionPerformed

    private void jButtonDeleteCachLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCachLyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteCachLyActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonShowInfoCachLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowInfoCachLyActionPerformed
//        jTFSearchByCMT.setText("");
//        this.settingTableShowDichTe();
//        showTableDichTeController.showDichTe(jTableKhaiDichTe);
    }//GEN-LAST:event_jButtonShowInfoCachLyActionPerformed

    private void jTableKhaiCachLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKhaiCachLyMouseClicked
//        DefaultTableModel model = (DefaultTableModel) jTableKhaiDichTe.getModel();
//        int rowIndex = jTableKhaiDichTe.getSelectedRow();
//        // display data
//        int ID = 0;
//        ID = (int) model.getValueAt(rowIndex, 0);
//        //        jTFSearchByCMT.setText(model.getValueAt(rowIndex, 0).toString());
//        String chungMinhThu = showTableNhanKhauController.searchCMTByID(ID).trim();
//        jTFSearchByCMT.setText(chungMinhThu);
    }//GEN-LAST:event_jTableKhaiCachLyMouseClicked

    private void jTableKhaiCachLyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKhaiCachLyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableKhaiCachLyMouseEntered

    private void jButtonXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemChiTietActionPerformed
        //        if (jTFSearchByCMT.getText().isEmpty()){
            //            JOptionPane.showMessageDialog(rootPane, "Chọn nhân khẩu muốn xem chi tiết", "Warning", JOptionPane.WARNING_MESSAGE);
            //        } else {
            //            String chungMinhThu = jTFSearchByCMT.getText().trim();
            //            InfoNhanKhau infoNhanKhau = new InfoNhanKhau(chungMinhThu);
            //            infoNhanKhau.setLocationRelativeTo(null);
            //            infoNhanKhau.setResizable(false);
            //            infoNhanKhau.setVisible(true);
            //        }
    }//GEN-LAST:event_jButtonXemChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CachLyManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CachLyManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CachLyManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CachLyManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CachLyManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAddCachLy;
    private javax.swing.JButton jButtonDeleteCachLy;
    private javax.swing.JButton jButtonEditCachLy;
    private javax.swing.JButton jButtonSearchCachLy;
    private javax.swing.JButton jButtonShowInfoCachLy;
    private javax.swing.JButton jButtonXemChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFSearchByCMT;
    private javax.swing.JTable jTableKhaiCachLy;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
