/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19_management_system.views;

import covid19_management_system.controllers.nhankhauController.DeleteNhanKhauController;
import covid19_management_system.controllers.nhankhauController.ShowTableNhanKhauController;
import covid19_management_system.views.NhanKhau.AddNhanKhau;
import covid19_management_system.views.NhanKhau.EditNhanKhau;
import covid19_management_system.views.NhanKhau.InfoNhanKhau;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HieuPhung
 */
public class NhanKhauManage extends javax.swing.JFrame {

    /**
     * Creates new form NhanKhauManage
     */
    ShowTableNhanKhauController showTableNhanKhauController = new ShowTableNhanKhauController();
    DeleteNhanKhauController deleteNhanKhauController = new DeleteNhanKhauController();

    public boolean isClose() {
        return close;
    }

    public void setClose(boolean close) {
        this.close = close;
    }

    
    private boolean close = false;

    public NhanKhauManage() {
        initComponents();
        this.setTitle("Quản lý nhân khẩu");

        this.settingTableShowNhanKhau();
        showTableNhanKhauController.showNhanKhau(jTableNhanKhau);

        // lắng nghe nhấn enter
        keyListenner(jTFSearchByCMT);

        // confirm de thuc hien dong
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đóng không ?", "Xác nhận thao tác", JOptionPane.YES_NO_OPTION) == 0) {
                    setClose(true);
                    dispose();
                }
            }
        });
    }

    // xu ly su kien nhan enter
    public void keyListenner(JTextField jtf) {
        jtf.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                // neu keycode == 10 ~ enter
                if (e.getKeyCode() == 10) {
                    timKiemNhanKhau();
                }
            }
        });
    }

    public void settingTableShowNhanKhau() {
        jTableNhanKhau.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTableNhanKhau.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTableNhanKhau.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTableNhanKhau.getColumnModel().getColumn(2).setPreferredWidth(125);
        jTableNhanKhau.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTableNhanKhau.getColumnModel().getColumn(4).setPreferredWidth(25);
        jTableNhanKhau.getColumnModel().getColumn(5).setPreferredWidth(190);
        jTableNhanKhau.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTFSearchByCMT = new javax.swing.JTextField();
        jButtonSearchInfoByCMT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonShowInfoNhanKhau = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanKhau = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonThemNhanKhau = new javax.swing.JButton();
        jButtonSuaNhanKhau = new javax.swing.JButton();
        jButtonXoaNhanKhau = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButtonXemChiTiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ THÔNG TIN NHÂN KHẨU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jTFSearchByCMT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonSearchInfoByCMT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSearchInfoByCMT.setText("TÌM KIẾM");
        jButtonSearchInfoByCMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchInfoByCMTActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TÌM KIẾM THEO CMT:");

        jButtonShowInfoNhanKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonShowInfoNhanKhau.setText("SHOW ALL");
        jButtonShowInfoNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowInfoNhanKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFSearchByCMT, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearchInfoByCMT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowInfoNhanKhau)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSearchByCMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchInfoByCMT)
                    .addComponent(jLabel2)
                    .addComponent(jButtonShowInfoNhanKhau))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jTableNhanKhau.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTableNhanKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID","Chứng minh thư", "Họ và tên", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại"
            }
        )

        // make the jtable cells not edittable
        {public boolean isCellEditTable(int row, int column){
            return false;
        }}

    );
    jTableNhanKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jTableNhanKhau.setGridColor(new java.awt.Color(255, 255, 0));
    jTableNhanKhau.setRowHeight(25);
    jTableNhanKhau.setSelectionBackground(new java.awt.Color(0, 102, 51));
    jTableNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableNhanKhauMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jTableNhanKhauMouseEntered(evt);
        }
    });
    jScrollPane1.setViewportView(jTableNhanKhau);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap()))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 484, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap()))
    );

    jPanel5.setBackground(new java.awt.Color(255, 204, 204));

    jButtonThemNhanKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonThemNhanKhau.setText("THÊM MỚI");
    jButtonThemNhanKhau.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonThemNhanKhauActionPerformed(evt);
        }
    });

    jButtonSuaNhanKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonSuaNhanKhau.setText("SỬA");
    jButtonSuaNhanKhau.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSuaNhanKhauActionPerformed(evt);
        }
    });

    jButtonXoaNhanKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonXoaNhanKhau.setText("XÓA");
    jButtonXoaNhanKhau.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonXoaNhanKhauActionPerformed(evt);
        }
    });

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("Nhập mã hộ khẩu:");

    jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton5.setText("SHOW");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButtonXemChiTiet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonXemChiTiet.setText("CHI TIẾT");
    jButtonXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonXemChiTietActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(0, 2, Short.MAX_VALUE))
                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonThemNhanKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSuaNhanKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonXoaNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(72, 72, 72)
            .addComponent(jButtonThemNhanKhau)
            .addGap(18, 18, 18)
            .addComponent(jButtonSuaNhanKhau)
            .addGap(18, 18, 18)
            .addComponent(jButtonXoaNhanKhau)
            .addGap(18, 18, 18)
            .addComponent(jButtonXemChiTiet)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addGap(18, 18, 18)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jButton5)
            .addGap(113, 113, 113))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemNhanKhauActionPerformed
        jTFSearchByCMT.setText("");
        AddNhanKhau temp = new AddNhanKhau();
        temp.setLocationRelativeTo(null);
        temp.setResizable(false);
        temp.setVisible(true);

        temp.getjButtonAddNhanKhau().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                temp.clickCreateButton();
                
                settingTableShowNhanKhau();
                showTableNhanKhauController.showNhanKhau(jTableNhanKhau);
            }
        });

    }//GEN-LAST:event_jButtonThemNhanKhauActionPerformed

    private void jButtonSuaNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaNhanKhauActionPerformed
        if (jTFSearchByCMT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Chọn nhân khẩu muốn chỉnh sửa", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String chungMinhThu = jTFSearchByCMT.getText().trim();
            EditNhanKhau temp = new EditNhanKhau(chungMinhThu);
            temp.setLocationRelativeTo(null);
            temp.setResizable(false);
            temp.setVisible(true);
            if (temp.getjRadioBHYT_YES().isSelected()) {
                temp.getjTFMaTheBHYT().setEnabled(true);
            }
            if (temp.getjRadioBHYT_NO().isSelected()) {
                temp.getjTFMaTheBHYT().setEnabled(false);
            }
            
            temp.getjButtonEditNhanKhau().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                temp.editNhanKhau();
                
                settingTableShowNhanKhau();
                showTableNhanKhauController.showNhanKhau(jTableNhanKhau);
            }
        });
        }
    }//GEN-LAST:event_jButtonSuaNhanKhauActionPerformed

    private void jButtonXoaNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaNhanKhauActionPerformed
        if (jTFSearchByCMT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Chọn nhân khẩu muốn xóa", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String chungMinhThu = jTFSearchByCMT.getText().trim();
            int ID = 0;
            ID = deleteNhanKhauController.searchIDFromCMT(chungMinhThu);
            if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không ?", "Xác nhận thao tác", JOptionPane.YES_NO_OPTION) == 0) {
                // xóa
                if (deleteNhanKhauController.deleteNhanKhau(ID)) {
                    JOptionPane.showMessageDialog(rootPane, "Successfully !", "Infomation", JOptionPane.INFORMATION_MESSAGE);
                    
                    this.settingTableShowNhanKhau();
                    showTableNhanKhauController.showNhanKhau(jTableNhanKhau);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Fail !", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                return;
            }
        }
    }//GEN-LAST:event_jButtonXoaNhanKhauActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTableNhanKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhanKhauMouseClicked

        DefaultTableModel model = (DefaultTableModel) jTableNhanKhau.getModel();
        int rowIndex = jTableNhanKhau.getSelectedRow();
        // display data
        jTFSearchByCMT.setText(model.getValueAt(rowIndex, 1).toString());
    }//GEN-LAST:event_jTableNhanKhauMouseClicked

    private void jButtonSearchInfoByCMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchInfoByCMTActionPerformed
        this.timKiemNhanKhau();
    }//GEN-LAST:event_jButtonSearchInfoByCMTActionPerformed

    public void timKiemNhanKhau() {
        if (jTFSearchByCMT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nhập chứng minh thư để tìm kiếm ", "Information", JOptionPane.INFORMATION_MESSAGE);
            this.settingTableShowNhanKhau();
            showTableNhanKhauController.showNhanKhau(jTableNhanKhau);
            return;
        } else {
            String chungMinhThu = jTFSearchByCMT.getText().trim();
//            System.out.println(chungMinhThu);
            if (checkDesignCMT()) {
                showTableNhanKhauController.showNhanKhauWithCMT(jTableNhanKhau, chungMinhThu);
                System.out.println("hello");
                if (jTableNhanKhau.getRowCount() == 0) {
                    this.settingTableShowNhanKhau();
                    showTableNhanKhauController.showNhanKhau(jTableNhanKhau);
                    JOptionPane.showMessageDialog(rootPane, "Không có nhân khẩu có CMT: " + chungMinhThu, "Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Tìm thấy. Hiện trên bảng kìa.", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
                return;
            }

        }
    }
    private void jButtonShowInfoNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowInfoNhanKhauActionPerformed
        jTFSearchByCMT.setText("");
        this.settingTableShowNhanKhau();
        showTableNhanKhauController.showNhanKhau(jTableNhanKhau);
    }//GEN-LAST:event_jButtonShowInfoNhanKhauActionPerformed

    private void jTableNhanKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhanKhauMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableNhanKhauMouseEntered

    private void jButtonXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemChiTietActionPerformed
        if (jTFSearchByCMT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Chọn nhân khẩu muốn xem chi tiết", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String chungMinhThu = jTFSearchByCMT.getText().trim();
            InfoNhanKhau infoNhanKhau = new InfoNhanKhau(chungMinhThu);
            infoNhanKhau.setLocationRelativeTo(null);
            infoNhanKhau.setResizable(false);
            infoNhanKhau.setVisible(true);
        }
    }//GEN-LAST:event_jButtonXemChiTietActionPerformed

    // check cac gia tri duoc nhap vao form
    private boolean checkDesignCMT() {
        // check dinh dang so chung minh thu
        try {
            long d = Long.parseLong(jTFSearchByCMT.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Số CMT không thể chứa các ký tự chữ cái", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        // kiem tra do dai cmt
        if (jTFSearchByCMT.getText().length() != 9 && jTFSearchByCMT.getText().length() != 12) {
            JOptionPane.showMessageDialog(rootPane, "Số CMT có 9 hoặc 12 số", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanKhauManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanKhauManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanKhauManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanKhauManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanKhauManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonSearchInfoByCMT;
    private javax.swing.JButton jButtonShowInfoNhanKhau;
    private javax.swing.JButton jButtonSuaNhanKhau;
    private javax.swing.JButton jButtonThemNhanKhau;
    private javax.swing.JButton jButtonXemChiTiet;
    private javax.swing.JButton jButtonXoaNhanKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFSearchByCMT;
    private javax.swing.JTable jTableNhanKhau;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
