/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid19_management_system.views;

import covid19_management_system.controllers.thongKeController.ThongKeController;
import covid19_management_system.models.ThongKeModel;
import covid19_management_system.views.NhanKhau.ShowInfoAllNhanKhau;
import covid19_management_system.views.ThongKe.ThongKeManage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HieuPhung
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    ThongKeModel thongKeModel = new ThongKeModel();
    ThongKeController thongKeController = new ThongKeController();

    public TrangChu() {
        initComponents();
        this.showThongKe();

        // confirm de thuc hien dong
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đóng không ?", "Xác nhận thao tác", JOptionPane.YES_NO_OPTION) == 0) {
                    dispose();
                }
            }
        });
    }

    public void showThongKe() {
        thongKeModel = thongKeController.showResultThongKe();

        jLabelDaKhaiBao.setText(Integer.valueOf(thongKeModel.getDaKhaiBao()).toString().trim());
        jLabelChuaKhaiBao.setText(Integer.valueOf(thongKeModel.getChuaKhaiBao()).toString().trim());
        jLabelTuVungDich.setText(Integer.valueOf(thongKeModel.getTuVungDich()).toString().trim());
        jLabelTiepXucCovid.setText(Integer.valueOf(thongKeModel.getTxCovid()).toString().trim());
        jLabelNguoiF0.setText(Integer.valueOf(thongKeModel.getMacCovid()).toString().trim());
        jLabelCachLy.setText(Integer.valueOf(thongKeModel.getCachLy()).toString().trim());
        jLabelCLTaiNha.setText(Integer.valueOf(thongKeModel.getCLTaiNha()).toString().trim());
        jLabelCLTapTrung.setText(Integer.valueOf(thongKeModel.getCLTapTrung()).toString().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonNhanKhau = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonDichTe = new javax.swing.JButton();
        jButtonCachLy = new javax.swing.JButton();
        jButtonThongKe = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDaKhaiBao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelChuaKhaiBao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTuVungDich = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelTiepXucCovid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelNguoiF0 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelCachLy = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelCLTaiNha = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelCLTapTrung = new javax.swing.JLabel();
        jButtonTuVungDich = new javax.swing.JButton();
        jButtonTxCovid = new javax.swing.JButton();
        jButtonMacCovid = new javax.swing.JButton();
        jButtonCLTaiNha = new javax.swing.JButton();
        jButtonCLTapTrung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TỔ DÂN PHỐ 7 PHƯỜNG LA KHÊ - HỆ THỐNG QUẢN LÝ THÔNG TIN PHÒNG TRÁNH COVID 19");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jButtonNhanKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNhanKhau.setText("NHÂN KHẨU");
        jButtonNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNhanKhauActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("HỆ THỐNG QUẢN LÝ:");

        jButtonDichTe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDichTe.setText("DỊCH TỄ");
        jButtonDichTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDichTeActionPerformed(evt);
            }
        });

        jButtonCachLy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCachLy.setText("CÁCH LY");
        jButtonCachLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCachLyActionPerformed(evt);
            }
        });

        jButtonThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonThongKe.setText("THỐNG KÊ");
        jButtonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCachLy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDichTe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNhanKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jButtonNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDichTe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("THÔNG TIN THU THẬP:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("1. KHAI BÁO DỊCH TỄ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("- Số người đã khai báo:");

        jLabelDaKhaiBao.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDaKhaiBao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDaKhaiBao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Chưa khai báo:");

        jLabelChuaKhaiBao.setBackground(new java.awt.Color(255, 255, 255));
        jLabelChuaKhaiBao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelChuaKhaiBao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("- Số người đi từ vùng dịch về:");

        jLabelTuVungDich.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTuVungDich.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTuVungDich.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("- Số người đã tiếp túc với người bệnh:");

        jLabelTiepXucCovid.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTiepXucCovid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTiepXucCovid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("2. KHAI BÁO CÁCH LY:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("- Số người mắc Covid-19:");

        jLabelNguoiF0.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNguoiF0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNguoiF0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("- Số người thực hiện cách ly:");

        jLabelCachLy.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCachLy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCachLy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Trong đó:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("+ Cách ly tại nhà:");

        jLabelCLTaiNha.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCLTaiNha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCLTaiNha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("+ Cách ly tập trung:");

        jLabelCLTapTrung.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCLTapTrung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCLTapTrung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonTuVungDich.setText("XEM");
        jButtonTuVungDich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTuVungDichActionPerformed(evt);
            }
        });

        jButtonTxCovid.setText("XEM");
        jButtonTxCovid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTxCovidActionPerformed(evt);
            }
        });

        jButtonMacCovid.setText("XEM");
        jButtonMacCovid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMacCovidActionPerformed(evt);
            }
        });

        jButtonCLTaiNha.setText("XEM");
        jButtonCLTaiNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLTaiNhaActionPerformed(evt);
            }
        });

        jButtonCLTapTrung.setText("XEM");
        jButtonCLTapTrung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLTapTrungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNguoiF0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMacCovid))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabelCLTaiNha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabelCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonCLTaiNha))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCLTapTrung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCLTapTrung))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTuVungDich, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel3))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel4)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDaKhaiBao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelChuaKhaiBao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTuVungDich))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTiepXucCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTxCovid)))
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDaKhaiBao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelChuaKhaiBao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTuVungDich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTuVungDich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTiepXucCovid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTxCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelNguoiF0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMacCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCachLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCLTaiNha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCLTaiNha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCLTapTrung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCLTapTrung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNhanKhauActionPerformed
        NhanKhauManage nhanKhauManage = new NhanKhauManage();
        nhanKhauManage.setLocationRelativeTo(null);
        nhanKhauManage.setResizable(false);
        nhanKhauManage.setVisible(true);

        nhanKhauManage.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                showThongKe();
            }
        });


    }//GEN-LAST:event_jButtonNhanKhauActionPerformed

    private void jButtonDichTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDichTeActionPerformed
        DichTeManage dichTeManage = new DichTeManage();
        dichTeManage.setLocationRelativeTo(null);
        dichTeManage.setResizable(false);
        dichTeManage.setVisible(true);

        dichTeManage.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                showThongKe();
            }
        });
    }//GEN-LAST:event_jButtonDichTeActionPerformed

    private void jButtonCachLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCachLyActionPerformed
        CachLyManage cachLyManage = new CachLyManage();
        cachLyManage.setLocationRelativeTo(null);
        cachLyManage.setResizable(false);
        cachLyManage.setVisible(true);

        cachLyManage.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                showThongKe();
            }
        });
    }//GEN-LAST:event_jButtonCachLyActionPerformed

    private void jButtonTuVungDichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTuVungDichActionPerformed
        ShowInfoAllNhanKhau temp = new ShowInfoAllNhanKhau();
        temp.setLocationRelativeTo(null);
        temp.setResizable(false);
        temp.setVisible(true);
        // sửa
        temp.setTitle("Liên quan vùng dịch");
        temp.getjLabelTitle().setText("Các nhân khẩu đi từ vùng dịch về");
        String query = "SELECT nhan_khau.ID, nhan_khau.chungMinhThu, nhan_khau.hoTen, nhan_khau.ngaySinh, nhan_khau.gioiTinh, nhan_khau.diaChi, nhan_khau.soDienThoai FROM nhan_khau INNER JOIN dich_te ON (nhan_khau.ID = dich_te.id_person) WHERE dich_te.tu_vung_dich = 1";
        temp.getShowTableNhanKhauController().showNhanKhauWithStr(temp.getjTableNhanKhau(), query.trim());

        temp.getjTableNhanKhau().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) temp.getjTableNhanKhau().getModel();
                int rowIndex = temp.getjTableNhanKhau().getSelectedRow();
                String chungMinhThu = model.getValueAt(rowIndex, 1).toString().trim();
                temp.getjTFShowCMT().setText(chungMinhThu);
            }
        });
//        temp.getjTFShowCMT().setText(chungMinhThu.trim());
//        temp.getjButtonCHOOSE().addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (temp.getjTFShowCMT().getText().isEmpty()) {
//                    JOptionPane.showMessageDialog(rootPane, "Lựa chọn nhân khẩu từ bảng trước !", "Warning", JOptionPane.WARNING_MESSAGE);
//                } else {
//                    // check cmt đã khai báo dịch tễ hay chưa ?
//                    int ID;
//                    ID = editNhanKhauController.searchIDFromCMT(chungMinhThu);
////                    System.out.println(ID);
//                    if (showTableDichTeController.checkIdDichTe(ID)) {
//                        JOptionPane.showMessageDialog(rootPane, "Nhân khẩu có CMT: " + chungMinhThu + " đã khai báo dịch tễ !\nChọn nhân khẩu khác để khai báo dịch tễ.", "Infomation", JOptionPane.INFORMATION_MESSAGE);
//                    } else {
//                        jTFChungMinhThu.setText(chungMinhThu.trim());
//
//                        temp.dispose();
//
//                        if (JOptionPane.showConfirmDialog(null, "Tìm thấy. Có muốn thực hiện khai báo dịch tễ\nvới nhân khẩu có CMT: " + chungMinhThu + " không ?", "Xác nhận thao tác", JOptionPane.YES_NO_OPTION) == 0) {
//                            NhanKhauModel nhanKhauModel = new NhanKhauModel();
//                            nhanKhauModel = editNhanKhauController.searchAllInfoNhanKhau(chungMinhThu);
//                            jTFChungMinhThu.setBackground(Color.GRAY);
//                            jTFChungMinhThu.setEditable(false);
//                            jTFHoVaTen.setText(nhanKhauModel.getHoTen().trim());
//                            jTFHoVaTen.setBackground(Color.gray);
//                            // date db to form
//                            try {
//                                Date dateIn = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(nhanKhauModel.getNgaySinh().toString());
//                                jDateCNgaySinh.setDate(dateIn);
//                            } catch (ParseException ex) {
//                                Logger.getLogger(AddDichTe.class.getName()).log(Level.SEVERE, null, ex);
//                            }
//                            // combobox
//                            jCoBoxGioiTinh.setSelectedIndex(nhanKhauModel.getGioiTinh());
//                            jTFQuocTich.setText(nhanKhauModel.getQuocTich().trim());
//                            jTFSoDienThoai.setText(nhanKhauModel.getSoDienThoai().trim());
//                            jTFEmail.setText(nhanKhauModel.getEmail().trim());
//                            jTFDiaChi.setText(nhanKhauModel.getDiaChi().trim());
//                            // radio
////                            jRadioBHYT_YES.setEnabled(true);
////                            jRadioBHYT_NO.setEnabled(true);
//                            if (nhanKhauModel.getCheckBHYT() == 1) {
//                                jRadioBHYT_YES.setSelected(true);
//                            } else if (nhanKhauModel.getCheckBHYT() == 0) {
//                                jRadioBHYT_NO.setSelected(true);
//                            }
//                            jTFMaTheBHYT.setText(nhanKhauModel.getMaTheBHYT().trim());
//                            jRadioBHYT_YES.setEnabled(false);
//                            jRadioBHYT_NO.setEnabled(false);
//
//                            setEnableDichTeFields(true);
//                        }
//                    }
//                }
//            }
//        });
    }//GEN-LAST:event_jButtonTuVungDichActionPerformed

    private void jButtonTxCovidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTxCovidActionPerformed
        ShowInfoAllNhanKhau temp = new ShowInfoAllNhanKhau();
        temp.setLocationRelativeTo(null);
        temp.setResizable(false);
        temp.setVisible(true);
        // sửa
        temp.setTitle("Tiếp xúc với người mắc Covid");
        temp.getjLabelTitle().setText("Các nhân khẩu tiếp xúc với người mắc Covid");
        String query = "SELECT nhan_khau.ID, nhan_khau.chungMinhThu, nhan_khau.hoTen, nhan_khau.ngaySinh, nhan_khau.gioiTinh, nhan_khau.diaChi, nhan_khau.soDienThoai FROM nhan_khau INNER JOIN dich_te ON (nhan_khau.ID = dich_te.id_person) WHERE dich_te.tx_benh = 1";
        temp.getShowTableNhanKhauController().showNhanKhauWithStr(temp.getjTableNhanKhau(), query.trim());

        temp.getjTableNhanKhau().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) temp.getjTableNhanKhau().getModel();
                int rowIndex = temp.getjTableNhanKhau().getSelectedRow();
                String chungMinhThu = model.getValueAt(rowIndex, 1).toString().trim();
                temp.getjTFShowCMT().setText(chungMinhThu);
            }
        });
    }//GEN-LAST:event_jButtonTxCovidActionPerformed

    private void jButtonMacCovidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMacCovidActionPerformed
        ShowInfoAllNhanKhau temp = new ShowInfoAllNhanKhau();
        temp.setLocationRelativeTo(null);
        temp.setResizable(false);
        temp.setVisible(true);
        // sửa
        temp.setTitle("Trường hợp FO");
        temp.getjLabelTitle().setText("Các nhân khẩu mắc Covid 19");
        String query = "SELECT nhan_khau.ID, nhan_khau.chungMinhThu, nhan_khau.hoTen, nhan_khau.ngaySinh, nhan_khau.gioiTinh, nhan_khau.diaChi, nhan_khau.soDienThoai FROM nhan_khau INNER JOIN cach_ly ON (nhan_khau.ID = cach_ly.IDNhanKhau) WHERE cach_ly.mucDoCL = 1";
        temp.getShowTableNhanKhauController().showNhanKhauWithStr(temp.getjTableNhanKhau(), query.trim());

        temp.getjTableNhanKhau().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) temp.getjTableNhanKhau().getModel();
                int rowIndex = temp.getjTableNhanKhau().getSelectedRow();
                String chungMinhThu = model.getValueAt(rowIndex, 1).toString().trim();
                temp.getjTFShowCMT().setText(chungMinhThu);
            }
        });
    }//GEN-LAST:event_jButtonMacCovidActionPerformed

    private void jButtonCLTaiNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLTaiNhaActionPerformed
        ShowInfoAllNhanKhau temp = new ShowInfoAllNhanKhau();
        temp.setLocationRelativeTo(null);
        temp.setResizable(false);
        temp.setVisible(true);
        // sửa
        temp.setTitle("Trường hợp cách ly");
        temp.getjLabelTitle().setText("Các nhân khẩu cách ly tại nhà");
        String query = "SELECT nhan_khau.ID, nhan_khau.chungMinhThu, nhan_khau.hoTen, nhan_khau.ngaySinh, nhan_khau.gioiTinh, nhan_khau.diaChi, nhan_khau.soDienThoai FROM nhan_khau INNER JOIN cach_ly ON (nhan_khau.ID = cach_ly.IDNhanKhau) WHERE cach_ly.loaiCL = 1";
        temp.getShowTableNhanKhauController().showNhanKhauWithStr(temp.getjTableNhanKhau(), query.trim());

        temp.getjTableNhanKhau().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) temp.getjTableNhanKhau().getModel();
                int rowIndex = temp.getjTableNhanKhau().getSelectedRow();
                String chungMinhThu = model.getValueAt(rowIndex, 1).toString().trim();
                temp.getjTFShowCMT().setText(chungMinhThu);
            }
        });
    }//GEN-LAST:event_jButtonCLTaiNhaActionPerformed

    private void jButtonCLTapTrungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLTapTrungActionPerformed
        ShowInfoAllNhanKhau temp = new ShowInfoAllNhanKhau();
        temp.setLocationRelativeTo(null);
        temp.setResizable(false);
        temp.setVisible(true);
        // sửa
        temp.setTitle("Trường hợp cách ly");
        temp.getjLabelTitle().setText("Các nhân khẩu cách ly tập trung");
        String query = "SELECT nhan_khau.ID, nhan_khau.chungMinhThu, nhan_khau.hoTen, nhan_khau.ngaySinh, nhan_khau.gioiTinh, nhan_khau.diaChi, nhan_khau.soDienThoai FROM nhan_khau INNER JOIN cach_ly ON (nhan_khau.ID = cach_ly.IDNhanKhau) WHERE cach_ly.loaiCL = 2";
        temp.getShowTableNhanKhauController().showNhanKhauWithStr(temp.getjTableNhanKhau(), query.trim());

        temp.getjTableNhanKhau().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) temp.getjTableNhanKhau().getModel();
                int rowIndex = temp.getjTableNhanKhau().getSelectedRow();
                String chungMinhThu = model.getValueAt(rowIndex, 1).toString().trim();
                temp.getjTFShowCMT().setText(chungMinhThu);
            }
        });
    }//GEN-LAST:event_jButtonCLTapTrungActionPerformed

    private void jButtonThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThongKeActionPerformed
        ThongKeManage thongKeManage = new ThongKeManage();
        thongKeManage.setLocationRelativeTo(null);
        thongKeManage.setResizable(false);
        thongKeManage.setVisible(true);

        thongKeManage.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                showThongKe();
            }
        });
    }//GEN-LAST:event_jButtonThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCLTaiNha;
    private javax.swing.JButton jButtonCLTapTrung;
    private javax.swing.JButton jButtonCachLy;
    private javax.swing.JButton jButtonDichTe;
    private javax.swing.JButton jButtonMacCovid;
    private javax.swing.JButton jButtonNhanKhau;
    private javax.swing.JButton jButtonThongKe;
    private javax.swing.JButton jButtonTuVungDich;
    private javax.swing.JButton jButtonTxCovid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCLTaiNha;
    private javax.swing.JLabel jLabelCLTapTrung;
    private javax.swing.JLabel jLabelCachLy;
    private javax.swing.JLabel jLabelChuaKhaiBao;
    private javax.swing.JLabel jLabelDaKhaiBao;
    private javax.swing.JLabel jLabelNguoiF0;
    private javax.swing.JLabel jLabelTiepXucCovid;
    private javax.swing.JLabel jLabelTuVungDich;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
